spring.application.name: rpg-project
logging.level.root: trace

spring:
  config:
    import: "optional:file:.env[.properties],optional:file:/etc/secrets/.env[.properties]"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRE_URL}
    username: ${POSTGRE_USERNAME}
    password: ${POSTGRE_PASSWORD}
  data:
    mongodb:
      uri: ${MONGO_URL}/rpg?retryWrites=true&w=majority&appName=rpg-project
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${NEXTAUTH_SECRET}

backend-api-key: ${BACKEND_API_KEY}