spring.application.name: rpg-project
logging.level.root: error

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRE_URL}
    username: ${POSTGRE_USERNAME}
    password: ${POSTGRE_PASSWORD}
  data:
    mongodb:
      uri: ${MONGO_URL}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SUPPORT_EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 3600000