CREATE TABLE USERS
(
    USERNAME   VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    LAST_NAME  VARCHAR(255),
    PRIMARY KEY (USERNAME)
);

CREATE TABLE CAMPAIGN
(
    NAME     VARCHAR(255),
    USERNAME VARCHAR(255),
    FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (NAME, USERNAME)
);