DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS
(
    USERNAME      TEXT UNIQUE NOT NULL,
    EMAIL         TEXT UNIQUE NOT NULL,
    FIRST_NAME    TEXT DEFAULT NULL,
    LAST_NAME     TEXT DEFAULT NULL,
    PASSWORD      TEXT DEFAULT NULL,
    DESCRIPTION   TEXT DEFAULT NULL,
    RPG_KNOWLEDGE TEXT DEFAULT NULL,
    PRIMARY KEY (USERNAME, EMAIL)
);

INSERT INTO USERS (USERNAME, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD)
VALUES ('alvin', 'mail@example.com', 'Alvin', 'Hamaide', 'password');