DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS
(
    ID            TEXT NOT NULL UNIQUE,
    USERNAME      TEXT NOT NULL,
    FIRST_NAME    TEXT DEFAULT NULL,
    LAST_NAME     TEXT DEFAULT NULL,
    INTRODUCTION  TEXT DEFAULT NULL,
    RPG_KNOWLEDGE TEXT DEFAULT NULL,
    PRIMARY KEY (ID)
);

INSERT INTO USERS (ID, USERNAME, FIRST_NAME, LAST_NAME, INTRODUCTION, RPG_KNOWLEDGE)
VALUES ('ID123', 'alvin', 'Alvin', 'Alvinson', NULL, NULL);