DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS
(
    USERNAME      TEXT,
    FIRST_NAME    TEXT DEFAULT NULL,
    LAST_NAME     TEXT DEFAULT NULL,
    INTRODUCTION  TEXT DEFAULT NULL,
    RPG_KNOWLEDGE TEXT DEFAULT NULL,
    PRIMARY KEY (USERNAME)
);

INSERT INTO USERS (USERNAME, FIRST_NAME, LAST_NAME, INTRODUCTION, RPG_KNOWLEDGE)
VALUES ('alvin', 'Alvin', 'Alvinson', NULL, NULL);